const DESTINATIONS = [
  {
    id: "bangkok",
    name: "Bangkok",
    country: "Thailand",
    region: "Asia",
    image: "assets/bangkok.svg",
    tagline: "Street food, culture and city energy — all in one trip.",
    facts: { language: "Thai", currency: "Thai Baht (THB)" },
    highlights: ["Wat Arun", "Yaowarat", "Chatuchak Weekend Market"],
    tips: ["Use BTS/MRT for many central areas.", "Plan outdoor stops around the heat."],
    bestFor: ["Food", "Culture", "Shopping"],
    myTake: "เมืองที่มีอะไรให้ทำแทบตลอดเวลา โดยเฉพาะถ้าชอบกินและเดินสำรวจหลายย่าน",
    rating: 4.5,
  },
  {
    id: "tokyo",
    name: "Tokyo",
    country: "Japan",
    region: "Asia",
    image: "assets/tokyo.svg",
    tagline:
      "Big-city energy with food, culture and neighbourhoods that feel completely different.",
    facts: { language: "Japanese", currency: "Japanese Yen (JPY)" },
    highlights: ["Asakusa", "Shibuya", "Meiji Shrine"],
    tips: [
      "Trains are usually the easiest way to move around.",
      "Group your day by neighbourhood.",
    ],
    bestFor: ["Food", "Shopping", "Culture"],
    myTake: "ไปกี่รอบก็ยังมีอะไรใหม่ให้ดู โดยเฉพาะสายกินและสายเดินเมือง",
    rating: 4.8,
  },
  {
    id: "sydney",
    name: "Sydney",
    country: "Australia",
    region: "Oceania",
    image: "assets/sydney.svg",
    tagline: "City life, beaches and nature within easy reach.",
    facts: { language: "English is widely used", currency: "Australian Dollar (AUD)" },
    highlights: ["Sydney Opera House", "Bondi Beach", "The Rocks"],
    tips: [
      "Public transport covers major visitor areas.",
      "Leave the CBD for a coastal walk if you have time.",
    ],
    bestFor: ["Beaches", "City Life", "Nature"],
    myTake: "ชอบตรงที่เช้าอยู่ในเมือง บ่ายไปทะเลหรือเดินธรรมชาติได้แบบไม่ต้องวางแผนใหญ่",
    rating: 4.6,
  },
  {
    id: "singapore",
    name: "Singapore",
    country: "Singapore",
    region: "Asia",
    image: "assets/singapore.svg",
    tagline: "Compact, easy to explore and packed with food and modern architecture.",
    facts: { language: "English · Malay · Mandarin · Tamil", currency: "Singapore Dollar (SGD)" },
    highlights: ["Gardens by the Bay", "Marina Bay", "Chinatown"],
    tips: [
      "MRT is useful for most visitor areas.",
      "Hawker centres are great for trying different dishes.",
    ],
    bestFor: ["Food", "Short Trips", "City Break"],
    myTake: "เหมาะกับทริปสั้นมาก เพราะเดินทางง่ายและจัดวันเที่ยวได้ตรงไปตรงมา",
    rating: 4.4,
  },
  {
    id: "paris",
    name: "Paris",
    country: "France",
    region: "Europe",
    image: "assets/paris.svg",
    tagline: "Art, architecture, cafés and neighbourhoods made for wandering.",
    facts: { language: "French", currency: "Euro (EUR)" },
    highlights: ["Eiffel Tower", "Louvre Museum", "Montmartre"],
    tips: [
      "Explore by neighbourhood instead of crossing the city repeatedly.",
      "Book popular attractions ahead when needed.",
    ],
    bestFor: ["Art", "Food", "Architecture"],
    myTake: "เสน่ห์ไม่ได้มีแค่แลนด์มาร์ก แต่คือการเดินเล่น คาเฟ่ และบรรยากาศแต่ละย่าน",
    rating: 4.5,
  },
  {
    id: "new-york",
    name: "New York",
    country: "USA",
    region: "North America",
    image: "assets/new-york.svg",
    tagline:
      "High-energy city life with food, entertainment and neighbourhoods that never feel the same.",
    facts: { language: "English is widely used", currency: "US Dollar (USD)" },
    highlights: ["Central Park", "Times Square", "Brooklyn Bridge"],
    tips: [
      "The subway is useful for covering longer distances.",
      "Plan activities by area to reduce backtracking.",
    ],
    bestFor: ["City Life", "Food", "Entertainment"],
    myTake: "วุ่นวายแบบมีเสน่ห์ และสนุกตรงที่เปลี่ยนย่านแล้วเหมือนได้อีกเมืองหนึ่ง",
    rating: 4.7,
  },
];
